---
- name: Setup SSH Key Authentication for Jenkins
  hosts: jenkins_master
  become: true
  roles:
    - ssh_setup

- name: Install Java on Jenkins Master
  hosts: jenkins_master
  become: true
  roles:
    - java_installation

- name: Install and Configure Jenkins Master
  hosts: jenkins_master
  become: true
  roles:
    - jenkins_master

