---
# tasks file for jenkins_master
- name: Install dependencies
  apt:
    name: ["ca-certificates", "curl", "gnupg"]
    state: present
    update_cache: yes

- name: Add Jenkins repository key
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: 0644

- name: Add Jenkins repository
  copy:
    content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/\n"
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Update apt package
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
